import { DoctorsImages, HospitalImages } from './DoctorsImages';

export const SliderData={
    'image': require('../images/main/Doctor19.png'),
    'title': 'Looking for Specialist Doctors?',
    'description': 'Schedule an appointment with our top doctors',
}
export const categories=(svgsCategories)=>
 {
    return     [
        { text: "Dentistry", icon: svgsCategories.teeth },
        { text: "Cardiology", icon: svgsCategories.heart },
        { text: "Pulmonology", icon: svgsCategories.lungs },
        { text: "General", icon: svgsCategories.general },
        { text: "Neurology", icon: svgsCategories.brain },
        { text: "Gastroenterologist", icon: svgsCategories.stomach },
        { text: "Laboratory", icon: svgsCategories.lab },
        { text: "Vaccination", icon: svgsCategories.vacine },
      ];
 }

export const AllHospitalsData = [
    {
      image: HospitalImages.hospital1,
      image_path: require('../images/main/Hospital1.png'),
      rating: "4.5",
      reviews: "7772",
      doctorName: "Melbrone Cardology",
      category: "Cardiolog",
      location: "Cardiology Center, USA",
    },
    {
      image: HospitalImages.hospital2,
      image_path: require('../images/main/Hospital2.png'),
      rating: "4.5",
      reviews: "7772",
      doctorName: "Melbrone General Health Care",
      category: "Health Care",
      location: "Cardiology Center, USA",
    },
    {
      image: HospitalImages.hospital3,
      image_path: require('../images/main/Hospital3.png'),
      rating: "4.5",
      reviews: "7772",
      doctorName: "Melbrone Neurology",
      category: "Neurology",
      location: "Cardiology Center, USA",
    },

  ];

  export const AllImages=[
    { image_path: require('../images/main/Doctor1.png'),},
    { image_path: require('../images/main/Doctor2.png'),},
    { image_path: require('../images/main/Doctor3.png'),},
    { image_path: require('../images/main/Doctor4.png'),},
    { image_path: require('../images/main/Doctor5.png'),},
    { image_path: require('../images/main/Doctor6.png'),},
    { image_path: require('../images/main/Doctor7.png'),},
    { image_path: require('../images/main/Doctor8.png'),},
    { image_path: require('../images/main/Doctor9.png'),},
    { image_path: require('../images/main/Doctor10.png'),},
    { image_path: require('../images/main/Doctor11.png'),},
    { image_path: require('../images/main/Doctor12.png'),},
    { image_path: require('../images/main/Doctor13.png'),},
    { image_path: require('../images/main/Doctor14.png'),},
    { image_path: require('../images/main/Doctor15.png'),},
    { image_path: require('../images/main/Doctor16.png'),},
    { image_path: require('../images/main/Doctor17.png'),},
    { image_path: require('../images/main/Doctor18.png'),},
    { image_path: require('../images/main/Doctor19.png'),},
    { image_path: require('../images/main/Doctor20.png'),},
    { image_path: require('../images/main/Doctor21.png'),},
    { image_path: require('../images/main/Doctor-22.png'),},
  ]
export const AllDoctorsData = [
    {
      imageId:7,
      image: DoctorsImages.doctor7,
      image_path: require('../images/main/Doctor7.png'),
      rating: "5",
      reviews: "1,872",
      doctorName: "Dr. David Patel",
      category: "Cardiologist",
      location: "Cardiology Center, USA",
    },
    {imageId:2,
      image: DoctorsImages.doctor2,
      image_path: require('../images/main/Doctor2.png'),
      rating: "4.9",
      reviews: "127",
      doctorName: "Dr. Jessica Turner",
      category: "Gynecologist",
      location: "Women's Clinic, Seattle, USA",
    },
    {imageId:3,
      image: DoctorsImages.doctor3,
       image_path: require('../images/main/Doctor3.png'),
      rating: "5",
      reviews: "5,223",
      doctorName: "Dr. Michael Johnson",
      category: "Orthopedic Surgery",
      location: "Maple Associates, NY, USA",
    },
    {imageId:4,
      image: DoctorsImages.doctor4,
       image_path: require('../images/main/Doctor4.png'),
      rating: "4.6",
      reviews: "405",
      doctorName: "Dr. Emily Walker",
      category: "Pediatrics",
      location: "Serenity Pediatrics Clinic, USA",
    },
    {imageId:6,
      image: DoctorsImages.doctor6,
       image_path: require('../images/main/Doctor6.png'),
      rating: "4.8",
      reviews: "980",
      doctorName: "Dr. Sarah Thompson",
      category: "Dermatologist",
      location: "Skin Care Clinic, Los Angeles, USA",
    },
    {imageId:5,
      image: DoctorsImages.doctor5,
       image_path: require('../images/main/Doctor5.png'),
      rating: "4.7",
      reviews: "765",
      doctorName: "Dr. Robert Anderson",
      category: "Neurologist",
      location: "Neuro Health Center, Chicago, USA",
    },
    {imageId:8,
      image: DoctorsImages.doctor8,
       image_path: require('../images/main/Doctor8.png'),
      rating: "4.9",
      reviews: "1,034",
      doctorName: "Dr. Linda Garcia",
      category: "Ophthalmologist",
      location: "Vision Care Clinic, Houston, USA",
    },
    {imageId:17,
      image: DoctorsImages.doctor17,
       image_path: require('../images/main/Doctor17.png'),
      rating: "5",
      reviews: "2,100",
      doctorName: "Dr. John Williams",
      category: "Dentist",
      location: "Bright Smiles Dental, Miami, USA",
    },
    {imageId:9,
      image: DoctorsImages.doctor9,
       image_path: require('../images/main/Doctor9.png'),
      rating: "4.8",
      reviews: "654",
      doctorName: "Dr. Rachel Brown",
      category: "Psychiatrist",
      location: "Mental Wellness Center, San Francisco, USA",
    },
    {imageId:16,
      image: DoctorsImages.doctor16,
       image_path: require('../images/main/Doctor16.png'),
      rating: "4.7",
      reviews: "834",
      doctorName: "Dr. Marryan Harris",
      category: "Endocrinologist",
      location: "Endocrine Health Associates, Boston, USA",
    },
  ];

  export const DentistryDoctors = [
    {
      imageId: 18,
      image: DoctorsImages.doctor18,
      image_path: require('../images/main/Doctor18.png'),
      rating: "5",
      reviews: "1,872",
      doctorName: "Dr. John Williams",
      category: "Dentist",
      location: "Bright Smiles Dental, Miami, USA",
    },
    {
      imageId: 14,
      image: DoctorsImages.doctor14,
      image_path: require('../images/main/Doctor14.png'),
      rating: "4.9",
      reviews: "2,100",
      doctorName: "Dr. Emily Stone",
      category: "Dentist",
      location: "Pearl Dental Clinic, Houston, USA",
    },
    {
      imageId: 6,
      image: DoctorsImages.doctor6,
      image_path: require('../images/main/Doctor6.png'),
      rating: "4.8",
      reviews: "1,547",
      doctorName: "Dr. Sarah Parker",
      category: "Dentist",
      location: "Dental Care Associates, Chicago, USA",
    },
    {
      imageId: 17,
      image: DoctorsImages.doctor17,
      image_path: require('../images/main/Doctor17.png'),
      rating: "4.7",
      reviews: "980",
      doctorName: "Dr. Michael Thompson",
      category: "Dentist",
      location: "Healthy Smiles Dental, New York, USA",
    },
    {
      imageId: 19,
      image: DoctorsImages.doctor19,
      image_path: require('../images/main/Doctor19.png'),
      rating: "5",
      reviews: "3,205",
      doctorName: "Dr. Jessica Lee",
      category: "Dentist",
      location: "Advanced Dental Clinic, San Francisco, USA",
    },
  ];
  
  export const CardiologyDoctors = [
    {
      imageId: 20,
      image: DoctorsImages.doctor20,
      image_path: require('../images/main/Doctor20.png'),
      rating: "5",
      reviews: "2,300",
      doctorName: "Dr. David Patel",
      category: "Cardiologist",
      location: "Cardiology Center, USA",
    },
    {
      imageId: 11,
      image: DoctorsImages.doctor11,
      image_path: require('../images/main/Doctor11.png'),
      rating: "4.9",
      reviews: "1,550",
      doctorName: "Dr. Jessica Turner",
      category: "Cardiologist",
      location: "Heart Health Clinic, New York, USA",
    },
    {
      imageId: 16,
      image: DoctorsImages.doctor16,
      image_path: require('../images/main/Doctor16.png'),
      rating: "5",
      reviews: "4,200",
      doctorName: "Dr. Mona Johnson",
      category: "Cardiologist",
      location: "Advanced Cardiac Care, Los Angeles, USA",
    },
    {
      imageId: 13,
      image: DoctorsImages.doctor13,
      image_path: require('../images/main/Doctor13.png'),
      rating: "4.8",
      reviews: "980",
      doctorName: "Dr. Sarah Adams",
      category: "Cardiologist",
      location: "CardioHealth Clinic, Chicago, USA",
    },
    {
      imageId: 17,
      image: DoctorsImages.doctor17,
      image_path: require('../images/main/Doctor17.png'),
      rating: "4.7",
      reviews: "1,800",
      doctorName: "Dr. Robert Anderson",
      category: "Cardiologist",
      location: "Heart & Vascular Institute, Houston, USA",
    },
  ];
  
  export const PulmonologyDoctors = [
    {
      imageId: 10,
      image: DoctorsImages.doctor10,
      image_path: require('../images/main/Doctor10.png'),
      rating: "5",
      reviews: "2,450",
      doctorName: "Dr. Emily Parker",
      category: "Pulmonologist",
      location: "Lung Health Center, New York, USA",
    },
    {
      imageId: 17,
      image: DoctorsImages.doctor17,
      image_path: require('../images/main/Doctor17.png'),
      rating: "4.8",
      reviews: "1,320",
      doctorName: "Dr. Michael Scott",
      category: "Pulmonologist",
      location: "Pulmonary Care Clinic, Chicago, USA",
    },
    {
      imageId: 11,
      image: DoctorsImages.doctor11,
      image_path: require('../images/main/Doctor11.png'),
      rating: "4.9",
      reviews: "2,200",
      doctorName: "Dr. Sarah Johnson",
      category: "Pulmonologist",
      location: "Breathe Well Clinic, Houston, USA",
    },
    {
      imageId: 3,
      image: DoctorsImages.doctor3,
      image_path: require('../images/main/Doctor3.png'),
      rating: "5",
      reviews: "3,100",
      doctorName: "Dr. Linda Anderson",
      category: "Pulmonologist",
      location: "Respiratory Wellness Center, Los Angeles, USA",
    },
    {
      imageId: 1,
      image: DoctorsImages.doctor1,
      image_path: require('../images/main/Doctor1.png'),
      rating: "4.7",
      reviews: "950",
      doctorName: "Dr. Robert Lee",
      category: "Pulmonologist",
      location: "Lung Health Associates, Miami, USA",
    },
  ];
  
  export const GeneralDoctors = [
    {
      imageId: 5,
      image: DoctorsImages.doctor5,
      image_path: require('../images/main/Doctor5.png'),
      rating: "5",
      reviews: "1,800",
      doctorName: "Dr. John Adams",
      category: "General Practitioner",
      location: "General Health Clinic, New York, USA",
    },
    {
      imageId: 4,
      image: DoctorsImages.doctor4,
      image_path: require('../images/main/Doctor4.png'),
      rating: "4.9",
      reviews: "1,500",
      doctorName: "Dr. Emily Thompson",
      category: "General Practitioner",
      location: "Wellness Clinic, Los Angeles, USA",
    },
    {
      imageId: 3,
      image: DoctorsImages.doctor3,
      image_path: require('../images/main/Doctor3.png'),
      rating: "4.7",
      reviews: "2,100",
      doctorName: "Dr. Sarah Lee",
      category: "General Practitioner",
      location: "Primary Care Center, Chicago, USA",
    },
    {
      imageId: 7,
      image: DoctorsImages.doctor7,
      image_path: require('../images/main/Doctor7.png'),
      rating: "4.6",
      reviews: "900",
      doctorName: "Dr. Robert Brown",
      category: "General Practitioner",
      location: "Health Hub Clinic, Miami, USA",
    },
    {
      imageId: 1,
      image: DoctorsImages.doctor1,
      image_path: require('../images/main/Doctor1.png'),
      rating: "5",
      reviews: "3,200",
      doctorName: "Dr. Jessica Davis",
      category: "General Practitioner",
      location: "Comprehensive Care Clinic, Boston, USA",
    },
  ];
  export const NeurologyDoctors = [
    {
      imageId: 9,
      image: DoctorsImages.doctor9,
      image_path: require('../images/main/Doctor9.png'),
      rating: "5",
      reviews: "1,950",
      doctorName: "Dr. Linda Walker",
      category: "Neurologist",
      location: "Neuro Health Center, New York, USA",
    },
    {
      imageId: 10,
      image: DoctorsImages.doctor10,
      image_path: require('../images/main/Doctor10.png'),
      rating: "4.9",
      reviews: "1,250",
      doctorName: "Dr. Michael Harris",
      category: "Neurologist",
      location: "Brain Care Clinic, Los Angeles, USA",
    },
    {
      imageId: 11,
      image: DoctorsImages.doctor11,
      image_path: require('../images/main/Doctor11.png'),
      rating: "5",
      reviews: "2,450",
      doctorName: "Dr. Sarah Miller",
      category: "Neurologist",
      location: "Advanced Neurology Center, Chicago, USA",
    },
    {
      imageId: 17,
      image: DoctorsImages.doctor17,
      image_path: require('../images/main/Doctor17.png'),
      rating: "4.8",
      reviews: "1,800",
      doctorName: "Dr. Robert Taylor",
      category: "Neurologist",
      location: "Neuro Specialists Clinic, Houston, USA",
    },
    {
      imageId: 19,
      image: DoctorsImages.doctor19,
      image_path: require('../images/main/Doctor19.png'),
      rating: "4.7",
      reviews: "950",
      doctorName: "Dr. Jessica Brown",
      category: "Neurologist",
      location: "Brain & Spine Clinic, Boston, USA",
    },
  ];
  
  export const GastroenterologistDoctors = [
    {
      imageId: 16,
      image: DoctorsImages.doctor16,
      image_path: require('../images/main/Doctor16.png'),
      rating: "5",
      reviews: "2,300",
      doctorName: "Dr. Emily Scott",
      category: "Gastroenterologist",
      location: "Gastro Health Center, New York, USA",
    },
    {
      imageId: 18,
      image: DoctorsImages.doctor18,
      image_path: require('../images/main/Doctor18.png'),
      rating: "4.8",
      reviews: "1,750",
      doctorName: "Dr. Michael Johnson",
      category: "Gastroenterologist",
      location: "Digestive Care Clinic, Chicago, USA",
    },
    {
      imageId: 19,
      image: DoctorsImages.doctor19,
      image_path: require('../images/main/Doctor19.png'),
      rating: "5",
      reviews: "2,100",
      doctorName: "Dr. Sarah Thompson",
      category: "Gastroenterologist",
      location: "Gut Health Clinic, Miami, USA",
    },
    {
      imageId: 20,
      image: DoctorsImages.doctor20,
      image_path: require('../images/main/Doctor20.png'),
      rating: "4.7",
      reviews: "1,400",
      doctorName: "Dr. Robert Lee",
      category: "Gastroenterologist",
      location: "Digestive Wellness Center, Houston, USA",
    },
    {
      imageId: 1,
      image: DoctorsImages.doctor1,
      image_path: require('../images/main/Doctor1.png'),
      rating: "4.9",
      reviews: "2,500",
      doctorName: "Dr. Jessica Davis",
      category: "Gastroenterologist",
      location: "Advanced GI Care, Los Angeles, USA",
    },
  ];
  
  export const LaboratoryDoctors = [
    {
      imageId: 3,
      image: DoctorsImages.doctor3,
      image_path: require('../images/main/Doctor3.png'),
      rating: "4.9",
      reviews: "1,980",
      doctorName: "Dr. Emily Brown",
      category: "Lab Technician",
      location: "Health Lab, New York, USA",
    },
    {
      imageId: 7,
      image: DoctorsImages.doctor7,
      image_path: require('../images/main/Doctor7.png'),
      rating: "4.7",
      reviews: "1,400",
      doctorName: "Dr. Michael Williams",
      category: "Lab Technician",
      location: "Clinical Lab Solutions, Boston, USA",
    },
    {
      imageId: 16,
      image: DoctorsImages.doctor16,
      image_path: require('../images/main/Doctor16.png'),
      rating: "4.8",
      reviews: "2,050",
      doctorName: "Dr. Sarah Lee",
      category: "Lab Technician",
      location: "Pathology Lab Center, Chicago, USA",
    },
    {
      imageId: 21,
      image: DoctorsImages.doctor21,
      image_path: require('../images/main/Doctor21.png'),
      rating: "5",
      reviews: "2,300",
      doctorName: "Dr. Robert Taylor",
      category: "Lab Technician",
      location: "LabCorp Health, Miami, USA",
    },
    {
      imageId: 1,
      image: DoctorsImages.doctor1,
      image_path: require('../images/main/Doctor1.png'),
      rating: "4.9",
      reviews: "1,600",
      doctorName: "Dr. Jessica Parker",
      category: "Lab Technician",
      location: "Diagnostic Labs, Los Angeles, USA",
    },
  ];
  
  export const VaccinationDoctors = [
    {
      imageId: 19,
      image: DoctorsImages.doctor19,
      rating: "5",
      reviews: "3,200",
      doctorName: "Dr. Linda White",
      category: "Vaccination Specialist",
      location: "Vaccine Care Clinic, New York, USA",
    },
    {
      imageId: 11,
      image: DoctorsImages.doctor11,
      rating: "4.8",
      reviews: "2,100",
      doctorName: "Dr. Sarah Brown",
      category: "Vaccination Specialist",
      location: "Immunization Center, Boston, USA",
    },
    {
      imageId: 20,
      image: DoctorsImages.doctor20,
      rating: "5",
      reviews: "2,800",
      doctorName: "Dr. Robert Davis",
      category: "Vaccination Specialist",
      location: "Vaccine Wellness Center, Los Angeles, USA",
    },
    {
      imageId: 16,
      image: DoctorsImages.doctor16,
      rating: "4.9",
      reviews: "1,750",
      doctorName: "Dr. Emily Thompson",
      category: "Vaccination Specialist",
      location: "Immunity Health Clinic, Chicago, USA",
    },
    {
      imageId: 1,
      image: DoctorsImages.doctor1,
      rating: "4.7",
      reviews: "1,400",
      doctorName: "Dr. Michael Anderson",
      category: "Vaccination Specialist",
      location: "Vaccine Hub Clinic, Houston, USA",
    },
  ];

      