import { DoctorsImages } from './DoctorsImages';

export const SliderData={
    'image': require('../images/main/Doctor11.png'),
    'title': 'Looking for Specialist Doctors?',
    'description': 'Schedule an appointment with our top doctors',
}
export const categories=(svgsCategories)=>
 {
    return     [
        { text: "Dentistry", icon: svgsCategories.teeth },
        { text: "Cardiology", icon: svgsCategories.heart },
        { text: "Pulmonology", icon: svgsCategories.lungs },
        { text: "General", icon: svgsCategories.general },
        { text: "Neurology", icon: svgsCategories.brain },
        { text: "Gastroenterologist", icon: svgsCategories.stomach },
        { text: "Laboratory", icon: svgsCategories.lab },
        { text: "Vaccination", icon: svgsCategories.vacine },
      ];
 }

export const AllDoctorsData = [
    {
      image: DoctorsImages.doctor7,
      rating: "5",
      reviews: "1,872",
      doctorName: "Dr. David Patel",
      category: "Cardiologist",
      location: "Cardiology Center, USA",
    },
    {
      image: DoctorsImages.doctor2,
      rating: "4.9",
      reviews: "127",
      doctorName: "Dr. Jessica Turner",
      category: "Gynecologist",
      location: "Women's Clinic, Seattle, USA",
    },
    {
      image: DoctorsImages.doctor3,
      rating: "5",
      reviews: "5,223",
      doctorName: "Dr. Michael Johnson",
      category: "Orthopedic Surgery",
      location: "Maple Associates, NY, USA",
    },
    {
      image: DoctorsImages.doctor4,
      rating: "4.6",
      reviews: "405",
      doctorName: "Dr. Emily Walker",
      category: "Pediatrics",
      location: "Serenity Pediatrics Clinic, USA",
    },
    {
      image: DoctorsImages.doctor6,
      rating: "4.8",
      reviews: "980",
      doctorName: "Dr. Sarah Thompson",
      category: "Dermatologist",
      location: "Skin Care Clinic, Los Angeles, USA",
    },
    {
      image: DoctorsImages.doctor5,
      rating: "4.7",
      reviews: "765",
      doctorName: "Dr. Robert Anderson",
      category: "Neurologist",
      location: "Neuro Health Center, Chicago, USA",
    },
    {
      image: DoctorsImages.doctor8,
      rating: "4.9",
      reviews: "1,034",
      doctorName: "Dr. Linda Garcia",
      category: "Ophthalmologist",
      location: "Vision Care Clinic, Houston, USA",
    },
    {
      image: DoctorsImages.doctor17,
      rating: "5",
      reviews: "2,100",
      doctorName: "Dr. John Williams",
      category: "Dentist",
      location: "Bright Smiles Dental, Miami, USA",
    },
    {
      image: DoctorsImages.doctor9,
      rating: "4.8",
      reviews: "654",
      doctorName: "Dr. Rachel Brown",
      category: "Psychiatrist",
      location: "Mental Wellness Center, San Francisco, USA",
    },
    {
      image: DoctorsImages.doctor16,
      rating: "4.7",
      reviews: "834",
      doctorName: "Dr. Marryan Harris",
      category: "Endocrinologist",
      location: "Endocrine Health Associates, Boston, USA",
    },
  ];

  export const DentistryDoctors = [
    {
      image: DoctorsImages.doctor18,
      rating: "5",
      reviews: "1,872",
      doctorName: "Dr. John Williams",
      category: "Dentist",
      location: "Bright Smiles Dental, Miami, USA",
    },
    {
      image: DoctorsImages.doctor14,
      rating: "4.9",
      reviews: "2,100",
      doctorName: "Dr. Emily Stone",
      category: "Dentist",
      location: "Pearl Dental Clinic, Houston, USA",
    },
    {
      image: DoctorsImages.doctor6,
      rating: "4.8",
      reviews: "1,547",
      doctorName: "Dr. Sarah Parker",
      category: "Dentist",
      location: "Dental Care Associates, Chicago, USA",
    },
    {
      image: DoctorsImages.doctor17,
      rating: "4.7",
      reviews: "980",
      doctorName: "Dr. Michael Thompson",
      category: "Dentist",
      location: "Healthy Smiles Dental, New York, USA",
    },
    {
      image: DoctorsImages.doctor19,
      rating: "5",
      reviews: "3,205",
      doctorName: "Dr. Jessica Lee",
      category: "Dentist",
      location: "Advanced Dental Clinic, San Francisco, USA",
    },
  ];
  
  export const CardiologyDoctors = [
    {
      image: DoctorsImages.doctor20,
      rating: "5",
      reviews: "2,300",
      doctorName: "Dr. David Patel",
      category: "Cardiologist",
      location: "Cardiology Center, USA",
    },
    {
      image: DoctorsImages.doctor11,
      rating: "4.9",
      reviews: "1,550",
      doctorName: "Dr. Jessica Turner",
      category: "Cardiologist",
      location: "Heart Health Clinic, New York, USA",
    },
    {
      image: DoctorsImages.doctor16,
      rating: "5",
      reviews: "4,200",
      doctorName: "Dr. Mona Johnson",
      category: "Cardiologist",
      location: "Advanced Cardiac Care, Los Angeles, USA",
    },
    {
      image: DoctorsImages.doctor13,
      rating: "4.8",
      reviews: "980",
      doctorName: "Dr. Sarah Adams",
      category: "Cardiologist",
      location: "CardioHealth Clinic, Chicago, USA",
    },
    {
      image: DoctorsImages.doctor17,
      rating: "4.7",
      reviews: "1,800",
      doctorName: "Dr. Robert Anderson",
      category: "Cardiologist",
      location: "Heart & Vascular Institute, Houston, USA",
    },
  ];
  export const PulmonologyDoctors = [
    {
      image: DoctorsImages.doctor10,
      rating: "5",
      reviews: "2,450",
      doctorName: "Dr. Emily Parker",
      category: "Pulmonologist",
      location: "Lung Health Center, New York, USA",
    },
    {
      image: DoctorsImages.doctor17,
      rating: "4.8",
      reviews: "1,320",
      doctorName: "Dr. Michael Scott",
      category: "Pulmonologist",
      location: "Pulmonary Care Clinic, Chicago, USA",
    },
    {
      image: DoctorsImages.doctor11,
      rating: "4.9",
      reviews: "2,200",
      doctorName: "Dr. Sarah Johnson",
      category: "Pulmonologist",
      location: "Breathe Well Clinic, Houston, USA",
    },
    {
      image: DoctorsImages.doctor3,
      rating: "5",
      reviews: "3,100",
      doctorName: "Dr. Linda Anderson",
      category: "Pulmonologist",
      location: "Respiratory Wellness Center, Los Angeles, USA",
    },
    {
      image: DoctorsImages.doctor1,
      rating: "4.7",
      reviews: "950",
      doctorName: "Dr. Robert Lee",
      category: "Pulmonologist",
      location: "Lung Health Associates, Miami, USA",
    },
  ];
  export const GeneralDoctors = [
    {
      image: DoctorsImages.doctor5,
      rating: "5",
      reviews: "1,800",
      doctorName: "Dr. John Adams",
      category: "General Practitioner",
      location: "General Health Clinic, New York, USA",
    },
    {
      image: DoctorsImages.doctor4,
      rating: "4.9",
      reviews: "1,500",
      doctorName: "Dr. Emily Thompson",
      category: "General Practitioner",
      location: "Wellness Clinic, Los Angeles, USA",
    },
    {
      image: DoctorsImages.doctor3,
      rating: "4.7",
      reviews: "2,100",
      doctorName: "Dr. Sarah Lee",
      category: "General Practitioner",
      location: "Primary Care Center, Chicago, USA",
    },
    {
      image: DoctorsImages.doctor7,
      rating: "4.6",
      reviews: "900",
      doctorName: "Dr. Robert Brown",
      category: "General Practitioner",
      location: "Health Hub Clinic, Miami, USA",
    },
    {
      image: DoctorsImages.doctor1,
      rating: "5",
      reviews: "3,200",
      doctorName: "Dr. Jessica Davis",
      category: "General Practitioner",
      location: "Comprehensive Care Clinic, Boston, USA",
    },
  ];
  export const NeurologyDoctors = [
    {
      image: DoctorsImages.doctor9,
      rating: "5",
      reviews: "1,950",
      doctorName: "Dr. Linda Walker",
      category: "Neurologist",
      location: "Neuro Health Center, New York, USA",
    },
    {
      image: DoctorsImages.doctor10,
      rating: "4.9",
      reviews: "1,250",
      doctorName: "Dr. Michael Harris",
      category: "Neurologist",
      location: "Brain Care Clinic, Los Angeles, USA",
    },
    {
      image: DoctorsImages.doctor11,
      rating: "5",
      reviews: "2,450",
      doctorName: "Dr. Sarah Miller",
      category: "Neurologist",
      location: "Advanced Neurology Center, Chicago, USA",
    },
    {
      image: DoctorsImages.doctor17,
      rating: "4.8",
      reviews: "1,800",
      doctorName: "Dr. Robert Taylor",
      category: "Neurologist",
      location: "Neuro Specialists Clinic, Houston, USA",
    },
    {
      image: DoctorsImages.doctor19,
      rating: "4.7",
      reviews: "950",
      doctorName: "Dr. Jessica Brown",
      category: "Neurologist",
      location: "Brain & Spine Clinic, Boston, USA",
    },
  ];
  export const GastroenterologistDoctors = [
    {
      image: DoctorsImages.doctor16,
      rating: "5",
      reviews: "2,300",
      doctorName: "Dr. Emily Scott",
      category: "Gastroenterologist",
      location: "Gastro Health Center, New York, USA",
    },
    {
      image: DoctorsImages.doctor18,
      rating: "4.8",
      reviews: "1,750",
      doctorName: "Dr. Michael Johnson",
      category: "Gastroenterologist",
      location: "Digestive Care Clinic, Chicago, USA",
    },
    {
      image: DoctorsImages.doctor19,
      rating: "5",
      reviews: "2,100",
      doctorName: "Dr. Sarah Thompson",
      category: "Gastroenterologist",
      location: "Gut Health Clinic, Miami, USA",
    },
    {
      image: DoctorsImages.doctor20,
      rating: "4.7",
      reviews: "1,400",
      doctorName: "Dr. Robert Lee",
      category: "Gastroenterologist",
      location: "Digestive Wellness Center, Houston, USA",
    },
    {
      image: DoctorsImages.doctor1,
      rating: "4.9",
      reviews: "2,500",
      doctorName: "Dr. Jessica Davis",
      category: "Gastroenterologist",
      location: "Advanced GI Care, Los Angeles, USA",
    },
  ];
  export const LaboratoryDoctors = [
    {
      image: DoctorsImages.doctor3,
      rating: "4.9",
      reviews: "1,980",
      doctorName: "Dr. Emily Brown",
      category: "Lab Technician",
      location: "Health Lab, New York, USA",
    },
    {
      image: DoctorsImages.doctor7,
      rating: "4.7",
      reviews: "1,400",
      doctorName: "Dr. Michael Williams",
      category: "Lab Technician",
      location: "Clinical Lab Solutions, Boston, USA",
    },
    {
      image: DoctorsImages.doctor16,
      rating: "4.8",
      reviews: "2,050",
      doctorName: "Dr. Sarah Lee",
      category: "Lab Technician",
      location: "Pathology Lab Center, Chicago, USA",
    },
    {
      image: DoctorsImages.doctor21,
      rating: "5",
      reviews: "2,300",
      doctorName: "Dr. Robert Taylor",
      category: "Lab Technician",
      location: "LabCorp Health, Miami, USA",
    },
    {
      image: DoctorsImages.doctor1,
      rating: "4.9",
      reviews: "1,600",
      doctorName: "Dr. Jessica Parker",
      category: "Lab Technician",
      location: "Diagnostic Labs, Los Angeles, USA",
    },
  ];
  export const VaccinationDoctors = [
    {
      image: DoctorsImages.doctor19,
      rating: "5",
      reviews: "3,200",
      doctorName: "Dr. Linda White",
      category: "Vaccination Specialist",
      location: "Vaccine Care Clinic, New York, USA",
    },
    {
      image: DoctorsImages.doctor11,
      rating: "4.8",
      reviews: "2,100",
      doctorName: "Dr. Sarah Brown",
      category: "Vaccination Specialist",
      location: "Immunization Center, Boston, USA",
    },
    {
      image: DoctorsImages.doctor20,
      rating: "5",
      reviews: "2,800",
      doctorName: "Dr. Robert Davis",
      category: "Vaccination Specialist",
      location: "Vaccine Wellness Center, Los Angeles, USA",
    },
    {
      image: DoctorsImages.doctor16,
      rating: "4.9",
      reviews: "1,750",
      doctorName: "Dr. Emily Thompson",
      category: "Vaccination Specialist",
      location: "Immunity Health Clinic, Chicago, USA",
    },
    {
      image: DoctorsImages.doctor1,
      rating: "4.7",
      reviews: "1,400",
      doctorName: "Dr. Michael Anderson",
      category: "Vaccination Specialist",
      location: "Vaccine Hub Clinic, Houston, USA",
    },
  ];
      

      