export const DoctorsImages = {
  doctor1: require('../images/main/Doctor1.png'),
  doctor2: require('../images/main/Doctor2.png'),
  doctor3: require('../images/main/Doctor3.png'),
  doctor4: require('../images/main/Doctor4.png'),
  doctor5: require('../images/main/Doctor5.png'),
  doctor6: require('../images/main/Doctor6.png'),
  doctor7: require('../images/main/Doctor7.png'),
  doctor8: require('../images/main/Doctor8.png'),
  doctor9: require('../images/main/Doctor9.png'),
  doctor10: require('../images/main/Doctor10.png'),
  doctor11: require('../images/main/Doctor11.png'),
  doctor12: require('../images/main/Doctor12.png'),
  doctor13: require('../images/main/Doctor13.png'),
  doctor14: require('../images/main/Doctor14.png'),
  doctor15: require('../images/main/Doctor15.png'),
  doctor16: require('../images/main/Doctor16.png'),
  doctor17: require('../images/main/Doctor17.png'),
  doctor18: require('../images/main/Doctor18.png'),
  doctor19: require('../images/main/Doctor19.png'),
  doctor20: require('../images/main/Doctor20.png'),
  doctor21: require('../images/main/Doctor21.png'),
};
